### ISSUE TITLE
App-specific config generation

### ISSUE THREAD

**Issue by LGUG2Z** [gladiator/komorebik#4]
Somebody shared this project in the komorebi community Discord server yesterday and I just wanted to drop a line to share how great I think this project is!

It would be nice to have a `komorebik` [config generation](https://github.com/LGUG2Z/komorebi/blob/master/komorebi-core/src/config_generation.rs) target which could consume the [application-specific-configuration](https://github.com/LGUG2Z/komorebi-application-specific-configuration) fixes to make it even easier for people to get up and running with `komorebik` as an alternative to AutoHotKey.

**Comment by gladiator** [comment]
Thank you very much for the kind words and another big thank you for all of the work on komorebi!

I'm not sure how you'd like to handle this, I can come up with a plan to do this entirely within `komorebik` so that you don't have to maintain any extra baggage in the main project, or I can submit a pull request and place it alongside the AutoHotKey config generation inside `komorebic`.

I'll be perfectly fine with whatever works for you!

**Comment by gladiator** [comment]
I've done some reading and it should be really easy to write the app-specific generator for configs within komorebik itself.  I'd just need access to some configuration generation data within `komorebi-core`.

https://github.com/LGUG2Z/komorebi/blob/63084141291145e1ae600fa1e1499d0e8d2b4e11/komorebi-core/src/config_generation.rs#L60-L82

If this data is made publicly accessible everything can be separately maintained and komorebik can generate it's own configurations.

**Comment by LGUG2Z** [comment]
@gladiator Those look like they are all publicly exported so you should be able to import them directly. 🎉

```
use komorebi_core::config_generation::IdWithIdentifier;
// etc.
```

**Comment by gladiator** [comment]
I meant that I need access to the data within those structures, sorry for not specifying!  I can't access any of the private members, like the app's `name` or `identifier`, needed to write to a configuration file.

I'll submit a pull request in a bit with the changes needed so anyone can write their own configurations if they need to!

**Comment by gladiator** [comment]
Thank you for getting that handled, I'll start working on the generator right away.

**Comment by gladiator** [comment]
Bang, added in https://github.com/gladiator/komorebik/commit/e00af41c6c25483b68739e7f5abc6451361401d7!  I'm hoping I didn't break anything.  I've been quite busy lately, but I may have some extra time soon so I can clean everything up and make things a bit friendlier for users.

Giving `komorebik` a valid path to `applications.yaml` will now generate the app-specific configuration alongside the existing configuration, I plan on adding some user help for the CLI part of things.

I've provided a pre-generated version in the `examples/` directory so users have something to start with.

I'm hoping this solves problems until I have time to clean up everything else as well.  Thanks for stopping by!
